### ISSUE TITLE
VS build error

### ISSUE THREAD

**Issue by kereslas** [CRVI/OpenCLIPP#13]
When building on VS an error occurs:

1>------ Build started: Project: OpenCLIPP-C++, Configuration: Debug Win32 ------
1>  Program.cpp
1>c:\i+d\opencl\openclipp-master\openclipp-master\c++\programs\program.cpp(75): error C3861: 'IsDebuggerPresent': identifier not found
========== Build: 0 succeeded, 1 failed, 4 up-to-date, 0 skipped ==========

In program.cpp there is the code (line 50):

#ifndef _MSC_VER
#define IsDebuggerPresent() false
#endif // _MSC_VER

And building fails as IsDebuggerPresent is not defined for VS compilers.

I suggest something like:

#ifndef _INTEL_CL_DEBUGGER_
#define IsDebuggerPresent() false
#else
#define IsDebuggerPresent() true
#endif // _INTEL_CL_DEBUGGER_

The user can define the macro if debugging is wanted ( /D "_INTEL_CL_DEBUGGER_" ). Options added by this code are only supported by Intel SDK, so identifying by compiler is not an option as you can have VS with NVIDIA or AMD SDK.

**Comment by AntAgna** [comment]
IsDebuggerPresent() is part of the Windows API : 
https://msdn.microsoft.com/en-us/library/windows/desktop/ms680345%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396

I had assumed incorrectly that Windows.h would end up included when building for Windows.
