### ISSUE TITLE
how to use method of blob

### ISSUE THREAD

**Issue by vevi1982** [CRVI/OpenCLIPP#17]
how to use mehtod of blob?
i can not get the correct result with it.
do u have a demo about it .

appreciate it

**Comment by AntAgna** [comment]
You need to call ocipComputeLabels() or OpenCLIPP::Blob::ComputeLabels() with an input image and an label image.
The input image must be 1 channel.
The input image is usually contains only 0 and 1.
The label image must be 1 channel 32 bit integer with the same dimension as the input image.
All non-zero pixels will be grouped with their neighbors and given a label number.
After calling the function, the label image will contain the label values for each pixel, and -1 (or 0xffffffff) for pixels that were 0 in the input image.

Afterward, you can call ocipRenameLabels() or OpenCLIPP::Blob::RenameLabels() to rename the labels from 0 to NbLabels-1.
If you want, you can then call ocipAddC(label, label, 1) to have 0 as background and 1 to NbLabels identifying the groups.

In the Bench program, BlobBench tests the blob functionality.
It works the same as ippiLabelMarkers although the order of the resulting labels might be different.
I have also tested with multiple complex images designed to test blob algorithms (which are not provided with the code).
It worked properly on AMD, NVIDIA and Intel OpenCL platforms.

What OpenCL platform and device are you using ?
Can you send me your image and your code ?

**Comment by vevi1982** [comment]
tks for reply.
my platform is  win10 ;vs2015; intel hd 4600.

when i run demo ,there's some error:

_Program build failed : 1:160:33: error: use of type 'double' requires cl_khr_fp64 extension to be enabled
cl-files/Base.h:46:27: note: expanded from macro 'CONCATENATE'
cl-files/Base.h:47:28: note: expanded from macro '_CONCATENATE'
<scratch space>:261:1: note: expanded from here
1:123:42: note: expanded from here
1:160:33: error: use of type 'double' requires cl_khr_fp64 extension to be enabled
cl-files/Base.h:46:27: note: expanded from macro 'CONCATENATE'
cl-files/Base.h:47:28: note: expanded from macro '_CONCATENATE'
<scratch space>:261:1: note: expanded from here
1:127:26: note: expanded from here
1:160:1: error: implicit declaration of function 'convert_double3' is invalid in OpenCL
1:129:34: note: expanded from here
cl-files/Base.h:46:27: note: expanded from macro 'CONCATENATE'
cl-files/Base.h:47:28: note: expanded from macro '_CONCATENATE'
<scratch space>:262:1: note: expanded from here
1:169:37: error: use of type 'double' requires cl_khr_fp64 extension to be enabled
cl-files/Base.h:46:27: note: expanded from macro 'CONCATENATE'
cl-files/Base.h:47:28: note: expanded from macro '_CONCATENATE'
<scratch space>:4:1: note: expanded from here
1:144:42: note: expanded from here
1:169:37: error: use of type 'double' requires cl_khr_fp64 extension to be enabled
cl-files/Base.h:46:27: note: expanded from macro 'CONCATENATE'
cl-files/Base.h:47:28: note: expanded from macro '_CONCATENATE'
<scratch space>:4:1: note: expanded from here
1:148:26: note: expanded from here

 - in file : cl-files/Convert.cl_

when i add this `#pragma OPENCL EXTENSION cl_khr_fp64 : enable` at the beginning of cl-files/Convert.cl.
it appear another error:
_Using device : Intel(R) HD Graphics 4600
Program build failed : 1:24:26: error: OpenCL extension 'cl_khr_fp64' is unsupported
1:161:1: error: implicit declaration of function 'convert_double3' is invalid in OpenCL
1:130:34: note: expanded from here
cl-files/Base.h:46:27: note: expanded from macro 'CONCATENATE'
cl-files/Base.h:47:28: note: expanded from macro '_CONCATENATE'
<scratch space>:265:1: note: expanded from here

 - in file : cl-files/Convert.cl
_

it seems the intel's opencl not support cl_khr_fp64.

**Comment by vevi1982** [comment]
In the bolb I want use it with opencv3.2.so i create to method to turn over cv::Mat with vector<unsigned char>.
void GetMatData(vector<unsigned char> & SourceData, cv::Mat& imgmat) {
	for (int j = 0; j < imgmat.rows; j++)
	{
		uchar *data = imgmat.ptr<uchar>(j);
		for (int i = 0; i < imgmat.cols*imgmat.channels(); i += imgmat.channels())
		{
			if (imgmat.channels() == 3) {
				SourceData.push_back(data[i + 2]);
				SourceData.push_back(data[i + 1]);
				SourceData.push_back(data[i]);
			}
			else if (imgmat.channels() == 1) {
				SourceData.push_back(data[i]);
			}
		}
	}
}


void GetMatFromData(vector<unsigned char>& ResultData, cv::Mat imgmat) {
	for (int j = 0; j < imgmat.rows; j++)
	{
		uchar *data = imgmat.ptr<uchar>(j);
		for (int i = 0; i < imgmat.cols*imgmat.channels(); i += imgmat.channels())
		{
			if (imgmat.channels() == 3) {
				data[i] = ResultData[j*imgmat.cols*imgmat.channels() + i + 2];
				data[i + 1] = ResultData[j*imgmat.cols*imgmat.channels() + i + 1];
				data[i + 2] = ResultData[j*imgmat.cols*imgmat.channels() + i];
			}
			else if (imgmat.channels() == 1) {
				data[i] = ResultData[j*imgmat.cols + i];
			}
		}
	}
}

then i craete a image:

void CreateBlobTestImage(vector<unsigned char> &SourceData,int Width,int Height) {
	for (uint y = 0; y < Height; y++)
		for (uint x = 0; x < Width; x++)
			SourceData.push_back(0);


	// Make white rectangles in the image
	for (int i = 0; i < 1; i++)
	{
		uint StartX = rand() % Width;
		uint EndX = rand() % (Width - StartX) + StartX;
		uint StartY = rand() % Height;
		uint EndY = rand() % (Height - StartY) + StartY;


		StartX += 60; EndY = EndY - 60; //StartY = StartY - 60;
		for (uint y = StartY; y < EndY; y++)
			for (uint x = StartX; x < EndX; x++)
				SourceData[y*Width + x] = 1;
	}
}

and use this to show the result 
cv::Scalar GetRandomColor()
{
	uchar r = 255 * (rand() / (1.0 + RAND_MAX));
	uchar g = 255 * (rand() / (1.0 + RAND_MAX));
	uchar b = 255 * (rand() / (1.0 + RAND_MAX));
	return cv::Scalar(b, g, r);
}
void LabelColor(const cv::Mat& labelImg, cv::Mat& colorLabelImg)
{
	if (labelImg.empty() ||labelImg.type() != CV_32SC1)
		return;

	std::map<int, cv::Scalar> colors;
	std::map<int, vector<cv::Point>> contours;
	int rows = labelImg.rows;
	int cols = labelImg.cols;


	colorLabelImg.release();
	colorLabelImg.create(rows, cols, CV_8UC3);
	colorLabelImg = cv::Scalar::all(0);


	for (int i = 0; i < rows; i++)
	{
		const int* data_src = (int*)labelImg.ptr<int>(i);
		uchar* data_dst = colorLabelImg.ptr<uchar>(i);
		for (int j = 0; j < cols; j++)
		{
			int pixelValue = data_src[j];
			if (pixelValue > 1)
			{
				if (colors.count(pixelValue) <= 0)
				{
					colors[pixelValue] = GetRandomColor();
					contours[pixelValue] = vector<cv::Point>();
				}
				contours[pixelValue].push_back(cv::Point(i, j));
				cv::Scalar color = colors[pixelValue];
				*data_dst++ = color[0];
				*data_dst++ = color[1];
				*data_dst++ = color[2];
			}
			else
			{
				//
				data_dst++;
				data_dst++;
				data_dst++;
			}
		}
	}
}

and the main theod is this 
int main_blobtest() {

	cv::Mat imgmat(512, 512, CV_8UC1, cv::Scalar(0, 0, 0));
	//
	vector<unsigned char> SourceData, ResultData;
	CreateBlobTestImage(SourceData,512,512);
	////GetMatData(SourceData, imgmat);
	GetMatFromData(SourceData, imgmat);
	//
	cv::imshow("ORIImage", imgmat);
	cv::waitKey();

	GetMatData(SourceData, imgmat);
	//
	SImage ImageInfo;
	ImageInfo.Channels = imgmat.channels();
	ImageInfo.Width = imgmat.cols;
	ImageInfo.Height = imgmat.rows;
	ImageInfo.Type = SImage::U8;
	ImageInfo.Step = ImageInfo.Width*ImageInfo.Channels;// CalculateStep(ImageInfo);
	ResultData.resize(SourceData.size(), -1);
	//
	COpenCL CL("Intel", CL_DEVICE_TYPE_GPU);//CL_DEVICE_TYPE_GPU
											 /*CL.SetClFilesPath("D:/OpenCV/OpenCLIPP-2015/cl-files/");*/
	CL.SetClFilesPath("cl-files/");
	// Display device name
	string Name = CL.GetDeviceName();
	printf("Using device : %s\n", Name.c_str());
	//

	// Create images in OpenCL device
	Image SourceImage(CL, ImageInfo, SourceData.data());
	ImageInfo.Type = SImage::S32;
	Image ResultImage(CL, ImageInfo, ResultData.data());
	//
	SourceImage.Send();   // Optional : Sends image to device memory - would be done automatically
						  //
	Blob blob(CL);
	blob.ComputeLabels(SourceImage, ResultImage, 8);
	blob.RenameLabels(ResultImage);
	//
	/*Transform kernel(CL);
	kernel.MirrorX(SourceImage, ResultImage);*/
	//
	ResultImage.Read(true);
	//data -》 Mat
	cv::Mat labelmat(imgmat.rows, imgmat.cols, CV_32SC1);
	GetMatFromData(ResultData, labelmat);
	//
	cv::imshow("ResultImage", labelmat);
	cv::Mat colorLabelImg;
	LabelColor(labelmat, colorLabelImg);
	cv::imshow("colorImg", colorLabelImg);

	printf("Success\n");


	cv::waitKey();
	//system("pause");
	return 0;


}

**Comment by vevi1982** [comment]
I see ur code in benchBlob.hpp and create a method to change the vector<unsinged char> to cv::Mat.

cv::Mat toMat(vector<unsigned char> SourceData, int rows,int cols ,int matType,int steps)
{
	return cv::Mat(rows, cols, matType, (void *)SourceData.data(),steps);
}

but the result is wrong .

is there something i wrong??

**Comment by AntAgna** [comment]
Sorry for the late answer, I have been busy.

Thank you for reporting the problem with Convert.cl on Intel platform.
I pushed a fix for it.

I have made a demo Blob program for you :
[Blob.zip](https://github.com/CRVI/OpenCLIPP/files/727900/Blob.zip)

Your function toMat looks good to me.
You just need to make sure to use the proper type (use cv::GetCVType) and step (use ResultImage.Step()).
