### ISSUE TITLE
Issue with Histogram

### ISSUE THREAD

**Issue by khbach** [CRVI/OpenCLIPP#18]
I am trying to use the histogram program.. The code I am using is:

#include <OpenCLIPP.hpp>
#include "png/lodepng.h"

using namespace std;
using namespace OpenCLIPP;

uint CalculateStep(const SImage& Img);

int main(int argc, char *argv[])
	{
		string Filename = "lena.png";
		SImage ImageInfo; 
		std::vector<unsigned char> SourceData;
		unsigned Status = lodepng::decode(SourceData, ImageInfo.Width,ImageInfo.Height, Filename, LCT_RGB);
		if (Status == 0)
			{
				ImageInfo.Channels = 3;
				ImageInfo.Type = SImage::U8;
				ImageInfo.Step = CalculateStep(ImageInfo);
			}

		printf("Check 1 \n");

		//Initialize OpenCL
  		COpenCL CL;
   		CL.SetClFilesPath("/home/kathleen/Downloads/OpenCLIPP-master/cl-files/");
   		Histogram Histogram(CL);

   		string Name = CL.GetDeviceName();
   		printf("Using device : %s\n", Name.c_str());
		printf("Check 2 \n");
		//Create OpenCL image
   		ColorImage SourceImage(CL, ImageInfo, SourceData.data());
		printf("Check 3 \n");

   		SourceImage.Send();   
		//Histogram
		uint Histogramptr[256];
		
		Histogram.Histogram1C(SourceImage,Histogramptr);
		printf("Check 4 \n");
		
		return 0;
	}

uint CalculateStep(const SImage& Img)
{
   uint Depth = 4;
   if (Img.Type < SImage::U16)
      Depth = 1;
   else if (Img.Type < SImage::U32)
      Depth = 2;

   return Img.Width * Img.Channels * Depth;
}	
The error I get is:
Program build failed : :36:51: error: invalid address space for argument to __kernel function
kernel void histogram_1C(INPUT_SPACE const SCALAR source, global uint * hist, uint src_step)
                                                  ^
:36:51: error: parameter may not be qualified with an address space
:73:49: error: invalid address space for argument to __kernel function
kernel void histogram_4C(INPUT_SPACE const TYPE source, global uint * hist, uint src_step)
                                                ^
:73:49: error: parameter may not be qualified with an address space

Thank you for your time.

**Comment by AntAgna** [comment]
Thank you for reporting this problem.

I have pushed a fix that should make Histogram work properly.

**Comment by khbach** [comment]
Thank you! I'll check it out.

**Comment by khbach** [comment]
Now the program compiles and runs but returns all zeros ( or whatever the histogram is initialized to).

**Comment by khbach** [comment]
yeah sorry I should have closed this. I fixed it and everything is working fine.
