### ISSUE TITLE
Histogram Issue

### ISSUE THREAD

**Issue by khbach** [CRVI/OpenCLIPP#19]
When I run the four channel histogram program the first channel appears to be correct but the other three channels have values that are way too large.  My code is below. Thank you for your time.
#include <OpenCLIPP.hpp>
#include "png/lodepng.h"

using namespace std;
using namespace OpenCLIPP;

uint CalculateStep(const SImage& Img);

int main(void)
	{
		   // Load image from file
   		   string FileName = "Skull.png";

   		   SImage ImageInfo;
   		   vector<unsigned char> SourceData;

   		   unsigned Status = lodepng::decode(SourceData, ImageInfo.Width, ImageInfo.Height, FileName, LCT_RGBA);

   		   if (Status == 0)
   			{
    			  // Load image from file succeded
    			  ImageInfo.Channels = 4;
    			  ImageInfo.Type = SImage::U8;
    			  ImageInfo.Step = CalculateStep(ImageInfo);
   			}
		//Initialize OpenCL
  		COpenCL CL;
   		CL.SetClFilesPath("/home/kathleen/Downloads/OpenCLIPP-master/cl-files/");
   		

   		string Name = CL.GetDeviceName();
   		printf("Using device : %s\n", Name.c_str());
		
		//Create OpenCL image
   		Image SourceImage(CL, ImageInfo, SourceData.data());

   		SourceImage.Send(); 
		Histogram Histogram(CL);  
		//Histogram
		uint Histogramptr[1024];
		
		Histogram.Histogram1C(SourceImage,Histogramptr);
		FILE *file;
		const char* mode = "w";
		file = fopen("Results.txt",mode);
		for (int i = 0; i < 4; i++)
		{
			for(int j = 0; j < 256; j++)
			{
			 fprintf(file," %u ", Histogramptr[(i*256)+j]);
			}
			fprintf(file,"\n \n");
		}
		
		return 0;
	}

**Comment by AntAgna** [comment]
Histogram1C should only be used for 1 channel images.
It may give incorrect results on images with multiple channels.

You can use Conversions::SelectChannel() or Conversions::ToGray() to convert to a 1 channel image.
Testing this made me find a few more bugs which I have now solved.

I have modified your program to test both Histogram1C and Histogram4C against a CPU implementation : 
[TestHistogram.zip](https://github.com/CRVI/OpenCLIPP/files/743644/TestHistogram.zip)
I get the same result using the library and the CPU implementation on both 1 channel and 4 channel.
Let me know if you obtain a different result.
