### ISSUE TITLE
Compiling an executable Demo on Ubuntu

### ISSUE THREAD

**Issue by ydirey** [CRVI/OpenCLIPP#20]
Hello dear developers, 

I'm trying to run your code on my Ubuntu 16.04 system with CUDA SDK(which includes OpenCL) installed.
So far I have been able to build your code successfully.
However I'm struggling to get the code to actually run as executable.

Which compiler should I use (gcc/g++/nvcc) and what options should I specify to generate an executable file?
Are there any further adjustments, that I have to make in order to actually test your code?
E.g. in the Demo.cpp file references some "lena.png" file that is not included in the repository.

Many thanks

Best regards,
Yaroslav

**Comment by AntAgna** [comment]
lena.png is a standard test image frequently used in vision software.
You can read about it and download the file from here : https://en.wikipedia.org/wiki/Lenna

You should use the `make` command to build both the library and the demo.
Like this : `# make`
make will read the makefile and use g++ to build the projects.

Let me know if you have any troubles.
