### ISSUE TITLE
some build error with vs2013

### ISSUE THREAD

**Issue by xylcbd** [CRVI/OpenCLIPP#8]
1,When I build this library with vs2013 and intel opencl sdk (opencl 2.0),"CL_USE_DEPRECATED_OPENCL_2_0_APIS" macro is request , or else will get a build error.

2,RandomImage.cpp Line48 , get a build error,modified to "std::uniform_int_distribution\<int\> Dist(0, 0xFF);" is ok

3,Visual Studio support #pragma message
#ifndef _MSC_VER  // Visual Studio does not support #warning
#warning "OpenCLIPP is not being built with clFFT - FFT operations will not be available"
#else
#pragma message("OpenCLIPP is not being built with clFFT - FFT operations will not be available")
#endif

**Comment by AntAgna** [comment]
Thank you for reporting these issues.
I have resolved them in these commits : 08cac74e936e16bf520949c9fa5ba400b94d0e9a 449443e8552113ae1cdc2d93934ebb042f49b10f d1f9fb816c8bbb0f6dca41fc324c69fa3fc9cfba
